# Generated by Django 3.2 on 2021-10-09 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='date',
        ),
    ]
